"""Repository helpers for the Purchase Order module (V0.4)."""

from __future__ import annotations

import sqlite3
from collections.abc import Sequence
from dataclasses import dataclass, field


@dataclass(slots=True)
class PurchaseOrderItem:
    """One line item of a purchase order."""

    id: int
    po_id: int
    description: str
    quantity: float
    purchase_rate: float
    created_at: str
    updated_at: str

    @property
    def amount(self) -> float:
        """Line value (quantity x purchase rate)."""
        return self.quantity * self.purchase_rate


@dataclass(slots=True)
class PurchaseOrder:
    """A purchase order belonging to exactly one party."""

    id: int
    party_id: int
    # The Party's own PO number, exactly as the vendor wrote it on their
    # document. It is required, it is never generated by the application, and
    # it does not have to be unique: two different parties may use the same
    # number (spec: a party's PO number is not a global internal id).
    po_number: str
    po_date: str
    source_document_path: str
    notes: str
    created_at: str
    updated_at: str
    #: Legacy column kept so older documents are not lost. The form no longer
    #: has a second reference field: the extracted reference now fills
    #: :attr:`po_number` itself, so this is only preserved, never re-entered.
    vendor_reference: str = ""
    party_name: str = ""
    item_count: int = 0
    #: Number of bills made from this PO (V0.6), shown in the PO list.
    bill_count: int = 0
    total_amount: float = 0.0
    items: list[PurchaseOrderItem] = field(default_factory=list)


def _validate_items(
    items: Sequence[tuple[str, float, float]],
) -> list[tuple[str, float, float]]:
    """Normalise PO item rows, raising ``ValueError`` when invalid."""
    cleaned: list[tuple[str, float, float]] = []
    for index, (description, quantity, rate) in enumerate(items, start=1):
        text = str(description).strip()
        try:
            qty = float(quantity)
            price = float(rate)
        except (TypeError, ValueError) as exc:
            raise ValueError(
                f"Item {index}: quantity and purchase rate must be numbers."
            ) from exc
        if not text:
            raise ValueError(f"Item {index}: description is required.")
        if qty <= 0:
            raise ValueError(f"Item {index}: quantity must be greater than zero.")
        if price < 0:
            raise ValueError(f"Item {index}: purchase rate cannot be negative.")
        cleaned.append((text, qty, price))
    if not cleaned:
        raise ValueError("Add at least one item with description and quantity.")
    return cleaned


def create_purchase_order(
    connection: sqlite3.Connection,
    *,
    party_id: int,
    po_date: str,
    items: Sequence[tuple[str, float, float]],
    po_number: str = "",
    source_document_path: str = "",
    notes: str = "",
    vendor_reference: str = "",
) -> int:
    """Insert a purchase order with its items and return the new id.

    *po_number* is the Party's own PO number, taken from their document. It is
    required and the application never invents one, so there is no fallback
    serial here (spec: the Party supplies the PO number). Two different parties
    may use the same number, so no uniqueness check is performed.
    *vendor_reference* is a legacy field: an extracted reference now fills
    *po_number* itself, so nothing new is written to it here.
    """
    number = str(po_number).strip()
    if not party_id:
        raise ValueError("Party is required.")
    if not number:
        raise ValueError("PO number is required.")
    if connection.execute(
        "SELECT 1 FROM parties WHERE id = ?", (party_id,)
    ).fetchone() is None:
        raise ValueError("Selected party does not exist.")
    cleaned = _validate_items(items)
    try:
        cursor = connection.execute(
            """
            INSERT INTO purchase_orders
                (party_id, po_number, po_date, source_document_path, notes,
                 vendor_reference)
            VALUES (?, ?, ?, ?, ?, '')
            """,
            (
                party_id,
                number,
                str(po_date).strip(),
                str(source_document_path).strip(),
                str(notes).strip(),
            ),
        )
        po_id = int(cursor.lastrowid)
        connection.executemany(
            "INSERT INTO po_items (po_id, description, quantity, purchase_rate)"
            " VALUES (?, ?, ?, ?)",
            [(po_id, text, qty, price) for text, qty, price in cleaned],
        )
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    return po_id


def list_purchase_orders(
    connection: sqlite3.Connection,
    search: str = "",
    party_id: int | None = None,
) -> list[PurchaseOrder]:
    """List POs, newest first, optionally filtered by party and search text.

    *search* matches the PO number or the party name (case-insensitive).
    """
    sql = """
        SELECT po.id, po.party_id, po.po_number, po.po_date,
               po.source_document_path, po.notes, po.created_at, po.updated_at,
               po.vendor_reference,
               p.name AS party_name,
               COUNT(i.id) AS item_count,
               COALESCE(SUM(i.quantity * i.purchase_rate), 0.0) AS total_amount,
               (SELECT COUNT(*) FROM bills AS b WHERE b.po_id = po.id) AS bill_count
        FROM purchase_orders AS po
        JOIN parties AS p ON p.id = po.party_id
        LEFT JOIN po_items AS i ON i.po_id = po.id
        WHERE 1 = 1
    """
    params: list[object] = []
    if party_id is not None:
        sql += " AND po.party_id = ?"
        params.append(party_id)
    text = str(search).strip()
    if text:
        sql += (
            " AND (po.po_number LIKE ? COLLATE NOCASE"
            " OR p.name LIKE ? COLLATE NOCASE)"
        )
        term = f"%{text}%"
        params.extend((term, term))
    sql += " GROUP BY po.id ORDER BY po.po_date DESC, po.id DESC"
    return [
        PurchaseOrder(
            id=row["id"],
            party_id=row["party_id"],
            po_number=row["po_number"],
            po_date=row["po_date"],
            source_document_path=row["source_document_path"],
            notes=row["notes"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            vendor_reference=row["vendor_reference"],
            party_name=row["party_name"],
            item_count=row["item_count"],
            bill_count=int(row["bill_count"] or 0),
            total_amount=float(row["total_amount"]),
        )
        for row in connection.execute(sql, params)
    ]


def _load_items(
    connection: sqlite3.Connection, po_id: int
) -> list[PurchaseOrderItem]:
    """Line items of one PO, in insertion order."""
    return [
        PurchaseOrderItem(
            id=row["id"],
            po_id=row["po_id"],
            description=row["description"],
            quantity=float(row["quantity"]),
            purchase_rate=float(row["purchase_rate"]),
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )
        for row in connection.execute(
            "SELECT * FROM po_items WHERE po_id = ? ORDER BY id", (po_id,)
        )
    ]


def items_by_ids(
    connection: sqlite3.Connection, item_ids: Sequence[int]
) -> dict[int, PurchaseOrderItem]:
    """Look up ``po_items`` rows by internal id (V0.5 item selection).

    Returns a mapping ``po_items.id -> PurchaseOrderItem``. Ids that no longer
    exist are simply absent, so callers can report them instead of guessing.
    """
    wanted = [int(item_id) for item_id in item_ids]
    if not wanted:
        return {}
    placeholders = ", ".join("?" for _ in wanted)
    return {
        int(row["id"]): PurchaseOrderItem(
            id=row["id"],
            po_id=row["po_id"],
            description=row["description"],
            quantity=float(row["quantity"]),
            purchase_rate=float(row["purchase_rate"]),
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )
        for row in connection.execute(
            f"SELECT * FROM po_items WHERE id IN ({placeholders})", wanted
        )
    }


def get_purchase_order(
    connection: sqlite3.Connection, po_id: int
) -> PurchaseOrder | None:
    """One PO with its items and totals, or None when the id is unknown."""
    row = connection.execute(
        """
        SELECT po.id, po.party_id, po.po_number, po.po_date,
               po.source_document_path, po.notes, po.created_at, po.updated_at,
               po.vendor_reference,
               p.name AS party_name
        FROM purchase_orders AS po
        JOIN parties AS p ON p.id = po.party_id
        WHERE po.id = ?
        """,
        (po_id,),
    ).fetchone()
    if row is None:
        return None
    po = PurchaseOrder(
        id=row["id"],
        party_id=row["party_id"],
        po_number=row["po_number"],
        po_date=row["po_date"],
        source_document_path=row["source_document_path"],
        notes=row["notes"],
        created_at=row["created_at"],
        updated_at=row["updated_at"],
        vendor_reference=row["vendor_reference"],
        party_name=row["party_name"],
    )
    po.items = _load_items(connection, po.id)
    po.item_count = len(po.items)
    po.total_amount = sum(item.amount for item in po.items)
    return po


def update_purchase_order(
    connection: sqlite3.Connection,
    po_id: int,
    *,
    party_id: int,
    po_number: str,
    po_date: str,
    items: Sequence[tuple[str, float, float]],
    source_document_path: str = "",
    notes: str = "",
    vendor_reference: str = "",
) -> bool:
    """Replace an existing PO (header + items). False when the id is missing."""
    if (
        connection.execute(
            "SELECT 1 FROM purchase_orders WHERE id = ?", (po_id,)
        ).fetchone()
        is None
    ):
        return False
    number = str(po_number).strip()
    if not party_id:
        raise ValueError("Party is required.")
    if not number:
        raise ValueError("PO number is required.")
    if (
        connection.execute(
            "SELECT 1 FROM parties WHERE id = ?", (party_id,)
        ).fetchone()
        is None
    ):
        raise ValueError("Selected party does not exist.")
    cleaned = _validate_items(items)
    try:
        # vendor_reference is left alone on purpose: it is a legacy column and
        # whatever a previous version captured there must not be erased.
        connection.execute(
            """
            UPDATE purchase_orders
               SET party_id = ?, po_number = ?, po_date = ?,
                   source_document_path = ?, notes = ?,
                   updated_at = datetime('now', 'localtime')
             WHERE id = ?
            """,
            (
                party_id,
                number,
                str(po_date).strip(),
                str(source_document_path).strip(),
                str(notes).strip(),
                po_id,
            ),
        )
        connection.execute("DELETE FROM po_items WHERE po_id = ?", (po_id,))
        connection.executemany(
            "INSERT INTO po_items (po_id, description, quantity, purchase_rate)"
            " VALUES (?, ?, ?, ?)",
            [(po_id, text, qty, price) for text, qty, price in cleaned],
        )
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    return True


def delete_purchase_order(connection: sqlite3.Connection, po_id: int) -> bool:
    """Delete a PO (items cascade). False when the id is missing."""
    if (
        connection.execute(
            "SELECT 1 FROM purchase_orders WHERE id = ?", (po_id,)
        ).fetchone()
        is None
    ):
        return False
    connection.execute("DELETE FROM purchase_orders WHERE id = ?", (po_id,))
    connection.commit()
    return True